### ISSUE TITLE
Cannot find backup in "path"

### ISSUE THREAD

**Issue by yu4L** [thehappydinoa/iOSRestrictionBruteForce#16]
Heyo! 'm trying to crack my screen time passcode for fun but, It's not working. It's saying that I don't have any backups on my computer, even tho I did one.
Here's the full output: 
`No device backups found.
Traceback (most recent call last):
  File "C:\Users\Omen\iOSRestrictionBruteForce\ioscrack.py", line 239, in <module>
    main()
  File "C:\Users\Omen\iOSRestrictionBruteForce\ioscrack.py", line 232, in main
    crack_hashes(find_hashes())
  File "C:\Users\Omen\iOSRestrictionBruteForce\ioscrack.py", line 124, in find_hashes
    device_paths = os.listdir(path)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\Omen\\AppData\\Roaming\\Apple Computer\\MobileSync\\Backup\\'`

**Comment by thehappydinoa** [comment]
Hey there,

You may have to manually specify the location on your hard drive. You can find this in iTunes.

**Comment by yungbeatz** [comment]
Well I found the actual path of my backup, but I don't know on how to combine it with your python code since I'm not really into python. 
I saw on another issue that you used python ioscrack.py -b "the guys path" but that also didn't work
