### ISSUE TITLE
Error: No module named requests....but requests 2.23.0 is installed

### ISSUE THREAD

**Issue by longeand** [thehappydinoa/iOSRestrictionBruteForce#17]
**UPDATE**
Disregard...running this "python3 ioscrack.py" works!

Cheers!

----------------------------------------------------------------------------------------------------------------------------------------------------------------

I've installed iOSRestrictionBruteForce in Ubuntu 20.04, but when I run "ioscrack.py" or "python ioscrack.py" I get the following:

Traceback (most recent call last):
  File "/usr/local/bin/ioscrack.py", line 11, in <module>
    import requests
ImportError: No module named requests

I've verified that Requests is installed in /usr/local/lib/Python3.8/dist-packages.
I also uninstalled Requests 2.23.0 and reinstalled with "pip3 install Requests==2.23.0"  which successfully reinstalled Requests 2.23.0
I'm unsure how to proceed in fixing this error...any help?

Thanks, Andy

**Comment by thehappydinoa** [comment]
Hey, it looks like you were able to fix this. I am going to go ahead and close this issue now.
