### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by dev-elijah** [thehappydinoa/iOSRestrictionBruteForce#19]
Hi there, going to use this software and when going to start running it only does this.. 
![image](https://user-images.githubusercontent.com/96087800/173979891-dd46c10c-27c7-42bb-8452-100c2691740d.png)
Please help ASAP.

**Comment by thehappydinoa** [comment]
Please read the readme's usage section: https://github.com/thehappydinoa/iOSRestrictionBruteForce#usage

Try running it with the `-c` option if you want it to be interactive.
