### ISSUE TITLE
how to Get the Base64 key and salt from the backup file in Computer.

### ISSUE THREAD

**Issue by getsecnow** [thehappydinoa/iOSRestrictionBruteForce#2]
can u please give me a detailed procedure on how to get the Base64 key and salt from the backup file in Computer.

**Comment by thehappydinoa** [comment]
Will do

**Comment by thehappydinoa** [comment]
@getsecnow I would like to refer you to the [wiki](https://github.com/thehappydinoa/iOSRestrictionBruteForce/wiki/Manually-find-restrictions-hash-and-salt)
