### ISSUE TITLE
Trouble following instructions

### ISSUE THREAD

**Issue by terminalN00b** [thehappydinoa/iOSRestrictionBruteForce#26]
Hello there,

I'm currently trying to break the passcode on my old iPhone 5. This tool sounds awesome, however, I'm struggling to follow the given instructions! I'm using a Macbook Pro with OS Catalina, and I already installed the required dependencies via terminal. Now what I don't understand is, how do you create a backup of a locked phone? iTunes or Finder wants you to input the passcode before proceeding. So I tried doing a backup with the libmobiledevice command, like stated in the guide, but that doesn't seem to work either.

Any suggestion? I'm really grateful for any help. Thanks!

**Comment by thehappydinoa** [comment]
Hey there, this tool is for the iOS restriction passcode not the iOS passcode. It assumes you have access to the device to preform a backup.
