### ISSUE TITLE
[QUESTION] Crack the iphone passcode from backup?

### ISSUE THREAD

**Issue by Anonyvius** [thehappydinoa/iOSRestrictionBruteForce#8]
Hey, it's me again. I thought about cracking the iPhone passcode from the backup. It's a more theoretical idea than practical. But the passcode is also stored inside the backup, so we just need to find and crack it. How about the implementation of Hashcat? I know 6 digit passcode is possible, but not many people know about this feature. SO we would just use your script, rewrite it a bit. And this should work. I know it's almost impossible. Just answer if you got any ideas about this.

- Ben

**Comment by thehappydinoa** [comment]
Ya I have no idea where to start with that

**Comment by thehappydinoa** [comment]
Closing due to it not being possible.
