### ISSUE TITLE
Getting "does not appear to contain a backup" as an error while sourcing the backup folder

### ISSUE THREAD

**Issue by design-bytes** [thehappydinoa/iOSRestrictionBruteForce#9]
Below is the command I used, please help if I am doing something wrong.

```
user@user-X555UA:~/Downloads/iOSRestrictionBruteForce-master$ python3 ioscrack.py -b '/media/user/DATA/backups/user-21-09-18/985a7c4008c6b6a06bb3c84dacbb71b31d845a2d/'

 iOSRestrictionBruteForce
 Written by thehappydinoa 

Traceback (most recent call last):
  File "ioscrack.py", line 216, in <module>
    main()
  File "ioscrack.py", line 205, in main
    crack_hashes(find_hashes(path=args.backup))
  File "ioscrack.py", line 115, in find_hashes
    devices.append(iDevice(device_path))
  File "ioscrack.py", line 76, in __init__
    raise ValueError("%s does not appear to contain a backup" % path)
ValueError: /media/user/DATA/backups/user-21-09-18/985a7c4008c6b6a06bb3c84dacbb71b31d845a2d/00 does not appear to contain a backup
```

**Comment by thehappydinoa** [comment]
Try `python3 ioscrack.py -b '/media/user/DATA/backups/user-21-09-18/'`

**Comment by design-bytes** [comment]
hi, I tried the same and got an error, please have a look below

 iOSRestrictionBruteForce
 Written by thehappydinoa 

Traceback (most recent call last):
  File "ioscrack.py", line 216, in <module>
    main()
  File "ioscrack.py", line 205, in main
    crack_hashes(find_hashes(path=args.backup))
  File "ioscrack.py", line 115, in find_hashes
    devices.append(iDevice(device_path))
  File "ioscrack.py", line 74, in __init__
    self.findSecretKeySalt()
  File "ioscrack.py", line 87, in findSecretKeySalt
    self.findSecretKeySalt(newPath=(not newPath))
  File "ioscrack.py", line 85, in findSecretKeySalt
    self.getSecretFromFile(path)
  File "ioscrack.py", line 92, in getSecretFromFile
    self.secret64 = line_list["RestrictionsPasswordKey"].asBase64()
**_KeyError: 'RestrictionsPasswordKey'_**

**Comment by thehappydinoa** [comment]
Are you on iOS 12?

**Comment by design-bytes** [comment]
> Are you on iOS 12?

Hi no, the phone backups were on 11.xx version, that i'm sure.
I tried this on nearly 7-8 full backups, no success.
Not sure what's the issue, I'll try again today, and will post.

**Comment by DivijV** [comment]
I am getting the same error and the backup is iOS 12, How do i get the restrictions passcode

**Comment by thehappydinoa** [comment]
@DivijV I will have to check into that one, but I may have to rewrite some of the code.

**Comment by DivijV** [comment]
This is what I'm getting


My Backup folder is now in iOSRestrictionsBruteForce Folder


python ioscrack.py -b Backup     

iOSRestrictionBruteForce
 Written by thehappydinoa 

Traceback (most recent call last):
  File "ioscrack.py", line 216, in <module>
    main()
  File "ioscrack.py", line 205, in main
    crack_hashes(find_hashes(path=args.backup))
  File "ioscrack.py", line 115, in find_hashes
    devices.append(iDevice(device_path))
  File "ioscrack.py", line 62, in __init__
    raise ValueError("%s is not a valid directory" % path)
ValueError: Backup/.DS_Store is not a valid directory


Hope you can help...
